[control]
13.206.69.204 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/keys/ansible-project-key.pem

[webservers]
13.234.110.222 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/keys/ansible-project-key.pem

[appservers]
35.154.243.108 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/keys/ansible-project-key.pem

[dbservers]
43.205.112.154 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/keys/ansible-project-key.pem

[servers:children]
webservers
appservers
dbservers

[servers:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_host_key_checking=False